name: CI
on:
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Lint code
        run: npm run lint
      
      - name: Run tests
        run: npm run test --workspaces --if-present
      
      - name: Build projects
        run: npm run build --workspaces --if-present

  # Trigger erweiterte CodeRabbit Review bei deep-review Label
  label-deep-review:
    if: contains(github.event.pull_request.labels.*.name, 'deep-review')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deep review label set – CodeRabbit führt erweitertes Review aus."
